[package]
name = "light-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty_jsc = "0.1.0"
rusty_jsc_sys = "0.1.0"
rusty_jsc_macros = "0.1.0"
rusty_v8 = "0.32.1"
tokio = { version = "1.35.1", features = ["full"] }
